### ISSUE TITLE
Add responsive behavior

### ISSUE THREAD

**Issue by upkarlidder** [Pyrrha-Platform/Pyrrha-Website#19]
Test the site for responsive screen sizes and add fixes appropriately.

Example:

Text on image should shrink:
![image](https://user-images.githubusercontent.com/3187457/125381246-6c5b3800-e348-11eb-8aba-aadfaeee00bd.png)

Images are not responsive:
![image](https://user-images.githubusercontent.com/3187457/125381280-7aa95400-e348-11eb-9d36-20a7e50a7b1c.png)

![image](https://user-images.githubusercontent.com/3187457/125381343-93196e80-e348-11eb-905e-be44f4f92943.png)

**Comment by krook** [comment]
Looks like this is still open as an issue. There should be some settings within the Carbon system we can take advantage of, if we're not already, as it has built in responsiveness support.

Another thing to take a pass at is to optimize the images for the web. Getting them down to 1MB or below is a good target. Photoshop may still have a "Save for web" option.

**Comment by giraudremi92** [comment]
@krook @upkarlidder 
Good day,

I could surely help you with this task.
I've already checked the CSS and the React app, we need to use différent image sizes and the grid system of carbon instead of custom css + use at least 3 media queries for wide screen tablet and smartphone.
https://www.carbondesignsystem.com/guidelines/2x-grid/implementation
Let me know if i can start working on it.

Thank you

**Comment by upkarlidder** [comment]
Absolutely @giraudremi92. +1 for using carbon grid instead of custom css 👍🏽  Thank you for your contribution!

**Comment by krook** [comment]
Welcome and thank you for your interest!

**Comment by giraudremi92** [comment]
Good Day everyone,
I've done some changes on the `CSS` and `React Js Components`.
I need your advice for one thing before i Pull and Request to you.

`First Breakpoint` : Wide Large screens and Middle screens (laptops)

Here a Screenshot from my laptop (left) and My Work Wide Screen 27" (right)

### The Banner : full Width and Height.

![Fullwidth](https://user-images.githubusercontent.com/61706260/130319819-7709f640-29a1-400e-99e8-d40567b07369.jpg)

I used a `Grid system` from the `Framework IBM` + some `custom CSS` then it's fully responsive

Tablet And Mobile :

![tablemobile](https://user-images.githubusercontent.com/61706260/130319976-aa3e43ce-86fb-4b69-8a0e-4afcde2d2464.jpg)

🆘 Here I need your help :

I was thinking on Mobile and Tablet put the Subtitle on the bottom of the Title then It does not overload the Banner.
Let me know
> Hardware and Software that monitors ....


### Team Section : 

I Changed the `grid` in the `React Component` it was not responsive (only 1 column), i've done `1 row and 4 columns`.

Wide Large screens and Middle screens 

Laptop (left) and My Work Wide Screen 27" (right)

![FullwidthTeam](https://user-images.githubusercontent.com/61706260/130320161-bd74315b-8537-4760-a6ae-12b552010a1e.jpg)



Tablet and Mobile :

![team_tablet_mobile](https://user-images.githubusercontent.com/61706260/130319999-ab2a76f2-1b72-43ad-9898-2ff6226e3c9f.jpg)

It still needs some adjustments (Section text ect) but it's a first shot.

**Comment by krook** [comment]
Very nice @giraudremi92! 

Yes, it is fine to do that for the subtitle. And it's looking great so far.

**Comment by giraudremi92** [comment]
@krook 
Ok thanks.
I' ll work on it asap

**Comment by krook** [comment]
Nicely done, thank you @giraudremi92!
