### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by upkarlidder** [Pyrrha-Platform/Pyrrha-Website#2]
@Aquijada52 @TaeBlack : add .gitignore file. You can get a template from here - https://github.com/github/gitignore/blob/master/Node.gitignore

**Comment by Aquijada52** [comment]
Someone must've done the bottom method without gitignore file, https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files 
when you do a github status, node_modules isn't tracked at all.
let me know if you would still like for me to add one in case it might be beneficial for the future.

**Comment by Aquijada52** [comment]
Did more digging, gitignore file is already in use.
